version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sukaix86/mdm-project-server
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FutabusClone
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=FutabusClone
    volumes:
      - ./init/mongo:/docker-entrypoint-initdb.d
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/password